name: Greetings

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for contributing to InstagramGrabber. Please remember to reference [Contributing.md](https://github.com/SukunDev/ngopinsta/blob/main/CONTRIBUTING.md)"
